"""initial migration

Revision ID: 9fd893406721
Revises: 
Create Date: 2024-11-03 08:55:41.098153

"""
from typing import Sequence, Union
from app.schema import EscrowStatus
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd893406721'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the enum type before adding the column
    escrow_status_enum = sa.Enum('FUNDS_HELD', 'FUNDS_RELEASED', name='escrowstatus')
    escrow_status_enum.create(op.get_bind())

    op.drop_index('ix_escrows_id', table_name='escrows')
    op.drop_table('escrows')
    op.add_column('deliveries', sa.Column('escrow_status', escrow_status_enum, nullable=True))
    op.add_column('deliveries', sa.Column('delivery_address', sa.String(), nullable=False))
    op.add_column('deliveries', sa.Column('delivery_date', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('orders', 'tracking_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('deliveries', 'created_at')
    op.drop_column('deliveries', 'delivery_date')
    op.drop_column('deliveries', 'delivery_address')
    op.drop_column('deliveries', 'escrow_status')
    op.create_table('escrows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_released', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='escrows_buyer_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='escrows_order_id_fkey'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name='escrows_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='escrows_pkey')
    )
    op.create_index('ix_escrows_id', 'escrows', ['id'], unique=False)

    # Drop the enum type after removing columns that use it
    escrow_status_enum = sa.Enum('FUNDS_HELD', 'FUNDS_RELEASED', name='escrowstatus')
    escrow_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
